#ifndef SHAREDMACROS_H_INCLUDED
#define SHAREDMACROS_H_INCLUDED


#define BACKGROUND_GREY Colour(48, 48, 48)

#define BACKGROUND_LIGHTGREY Colour(68, 68, 68)

#define UI_PADDING 20

#define TRACK_WIDTH_RATIO 0.25

#define PLAYERBAR_HEIGHT 50

#define LABELBAR_HEIGHT 40

#define LABELBAR_PADDING 5

#define TRACKNOTE_HEIGHT 100



#endif  // SHAREDMACROS_H_INCLUDED
